In [5]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.0.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [6]:
import numpy as np
import time

In [7]:
a_np=np.arange(10000000)
b_np=np.arange(10000000)
start=time.time()
result_np=a_np+b_np
end=time.time()
print("Numpy array Time:", end -start)

Numpy array Time: 0.046892642974853516


In [8]:
a=np.array([1,2,3,4,5,6])
print("1D Array:",a)
a.shape

1D Array: [1 2 3 4 5 6]


(6,)

(n,) = 1D array with n elements

(1, n) = 2D array with 1 row and n columns

(n, 1) = 2D array with n rows and 1 column

(n,) ≠ (n, 1) ≠ (1, n) even though they all have n total elements

#### Slicing and Reshaping Arrays

* Slicing helps extract parts of arrays.
* Reshaping changes the shape without changing data.

In [9]:
import numpy as np

arr = np.arange(12)
print("Original:", arr)

#Slicing
print("First 5:", arr[:5])
print("Last 3:", arr[-3:])

print("3rd to 7th", arr[3:8])


Original: [ 0  1  2  3  4  5  6  7  8  9 10 11]
First 5: [0 1 2 3 4]
Last 3: [ 9 10 11]
3rd to 7th [3 4 5 6 7]


In [10]:
#reshape to 3*4
reshaped=arr.reshape(3,4)
print("reshape 3*4:\n", reshaped)

reshape 3*4:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [11]:
print("last column", reshaped[:,-1])

last column [ 3  7 11]


In [12]:
print("last row", reshaped[-1])

last row [ 8  9 10 11]


In [13]:
print("last column", reshaped[:,-2])

last column [ 2  6 10]


In [14]:
reshaped[0][-1]=55

In [15]:
reshaped

array([[ 0,  1,  2, 55],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [16]:
type(reshaped[:,-1])

numpy.ndarray

##### Vectorized Operations & Broadcasting

* `Vectorized operations` allow fast element-wise operations.
* `Broadcasting` enables operations between arrays of different shapes.

# Two dimensions are compatible when:
They are equal, OR
One of them is 1.

In [17]:
x=np.array([1,2,3])
y=np.array([4,5,6])
print("addition",x+y)
print("multiplication",x*y)
print("scalar multiplication",x*10)

addition [5 7 9]
multiplication [ 4 10 18]
scalar multiplication [10 20 30]


In [18]:
# Broadcasting example
mat = np.ones((2, 3), dtype=int)
print(mat)

print("-------")
vec = np.array([1, 2, 3])
print("Broadcasted Addition:\n", mat + vec)

[[1 1 1]
 [1 1 1]]
-------
Broadcasted Addition:
 [[2 3 4]
 [2 3 4]]


In [19]:
vect = np.array([1, 2, 3])
vectr = np.array([[1, 2, 3],[4, 5, 6]])
print("Broadcasted Addition:\n", vect + vectr)
scalar=5
print("Broadcasted scalar multiplication:\n", scalar * vectr)

Broadcasted Addition:
 [[2 4 6]
 [5 7 9]]
Broadcasted scalar multiplication:
 [[ 5 10 15]
 [20 25 30]]


In [20]:
data = np.array([[80, 85, 90],
                 [70, 75, 65],
                 [88, 92, 95]])

print("Mean:", np.mean(data))
print("Sum:", np.sum(data))
print("standard deviation:", np.std(data))
print("Minimum:", np.min(data))
print("Maximum:", np.max(data))

Mean: 82.22222222222223
Sum: 740
standard deviation: 9.795438595792973
Minimum: 65
Maximum: 95


In [21]:
print("Mean per student:", np.mean(data,axis=1)) #1 vaneko row

Mean per student: [85.         70.         91.66666667]


In [22]:
print("Mean per subject:", np.mean(data,axis=0)) #0 vaneko column

Mean per subject: [79.33333333 84.         83.33333333]


##### Boolean Indexing & Filtering

- Use boolean masks to filter arrays based on conditions.

- In NumPy, you can pass a boolean array inside square brackets to filter the original array. This is called boolean indexing.

In [23]:
scores = np.array([80, 85, 90 ,96,88,78])
high_scores= scores[scores>70]
print("scores>70:",high_scores)
even_scores =scores[scores%2==0]
print("scores>70:",even_scores)
odd_scores =scores[scores%2!=0]
print("scores>70:",odd_scores)

scores>70: [80 85 90 96 88 78]
scores>70: [80 90 96 88 78]
scores>70: [85]


In [24]:
#matrix multiplication
mat1 = np.array([[1, 2], [3, 4]])
mat2 = np.array([[2, 0], [1, 2]])
result=np.dot(mat1,mat2)
print(f"dot product is {result}")

dot product is [[ 4  4]
 [10  8]]


Activity: Matrix Calculations and Score Filtering
Given a 5x4 matrix of student scores (rows: students, columns: subjects), find:

Average score per student
Students who scored above 75 in any subject
Selection deleted


In [25]:

import numpy as np
np.random.seed(0)
student_scores=np.random.randint(50,100,size=(5,4))
print(student_scores)
print("average score:", np.mean(student_scores,axis=1))

[[94 97 50 53]
 [53 89 59 69]
 [71 86 73 56]
 [74 74 62 51]
 [88 89 73 96]]
average score: [73.5  67.5  71.5  65.25 86.5 ]


In [26]:
print(student_scores)

[[94 97 50 53]
 [53 89 59 69]
 [71 86 73 56]
 [74 74 62 51]
 [88 89 73 96]]


In [27]:
students_above_75 = np.any(student_scores > 75, axis=1)
students_above_75

array([ True,  True,  True, False,  True])

## Assignment: Analyze Numeric Data and Filter Top 10% Scores

Given a list of exam scores for 30 students, write a program to:
- Compute the mean and standard deviation
- Filter scores in the top 10%

In [3]:
import numpy as np
np.random.seed(0)
student_scores=np.random.randint(50,100,size=(30,1))
print(student_scores)

[[94]
 [97]
 [50]
 [53]
 [53]
 [89]
 [59]
 [69]
 [71]
 [86]
 [73]
 [56]
 [74]
 [74]
 [62]
 [51]
 [88]
 [89]
 [73]
 [96]
 [74]
 [67]
 [87]
 [75]
 [63]
 [58]
 [59]
 [70]
 [66]
 [55]]


In [2]:
print("Mean:", np.mean(student_scores))

print("standard deviation:", np.std(student_scores))

Mean: 73.275
standard deviation: 15.100200053862421


In [5]:
threshold=np.percentile(student_scores,10)
top_scores=student_scores[student_scores <=threshold]

print("top 10% threshold",threshold)
print("top 10% scores",top_scores)

top 10% threshold 53.0
top 10% scores [50 53 53 51]


In [9]:
x=np.array([1,2,3,4])
copy_x =x.copy()
view_x =x.view()

In [13]:
copy_x[-2]=33
print("x",x)
print("copy_x",copy_x)



view_x[-3]=22
print("x",x)
print("view_x",view_x)


x [ 1 22  3  4]
copy_x [ 1  2 33  4]
x [ 1 22  3  4]
view_x [ 1 22  3  4]


In [22]:
np.shares_memory(x, copy_x)




    

False

In [23]:
np.shares_memory(x, view_x)

True

## Join, Split, Sort, Filter, Search

Manipulating the structure and content of arrays is a **core skill in NumPy**.

---

### 🔹 Joining

Putting the contents of two or more arrays into a single array using:

- `np.concatenate()`
- `np.stack()`

In [24]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

joined = np.concatenate((a, b))
print(joined)

[1 2 3 4 5 6]


In [26]:
stack = np.stack((a, b))
print(stack)

[[1 2 3]
 [4 5 6]]


In [27]:
joined.ndim

1

In [28]:
stack.ndim

2

### 🔹 Splitting

Breaking one array into multiple arrays using:

- `np.array_split(data, number)` Split 1D or 2D arrays into equal parts

In [44]:
arr_big = np.array([1, 2, 3, 4, 5, 6])
split_arry=np.array_split(arr_big, 3)
print(split_arry)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [43]:
print(split_arry[1])

[3 4]


In [46]:
unsorted = np.array([3,2,1,4,2,9])
sorted_arr =np.sort(unsorted)
print(unsorted)
print(sorted_arr)

[3 2 1 4 2 9]
[1 2 2 3 4 9]


In [49]:
arr_2d_rand = np.array([[3,2,4],[5,0,1]])
sorted_arry =np.sort(arr_2d_rand)
print(sorted_arry)

[[2 3 4]
 [0 1 5]]


In [50]:
# --- SEARCHING ---
unsorted = np.array([3, 1, 4, 2, 5, 4])
idx = np.where(unsorted == 4)
print(f"Index where value is 4: {idx}")

Index where value is 4: (array([2, 5]),)


In [51]:
# Searchsorted (Binary Search) - finds where value should be inserted to maintain order
sorted_base = np.array([1, 3, 5, 7])

insert_idx = np.searchsorted(sorted_base, 4)
print(f"Insert 4 into {sorted_base} at index: {insert_idx}")

Insert 4 into [1 3 5 7] at index: 2


In [52]:
sorted_base[2]=4

In [53]:
print(sorted_base)

[1 3 4 7]


## 3. Working with Missing Data in NumPy

Unlike **Pandas**, standard **NumPy integer arrays** do not support missing values (`NaN`).  
To work with missing data, the array usually needs to be of type **float** or **object**.

### 🔹 Key Concepts

- **`np.nan`**  
  Represents a missing or undefined value (*Not a Number*).

- **`np.isnan()`**  
  Checks which elements are missing.

- **`np.nansum()`**, **`np.nanmean()`**  
  Perform arithmetic operations while safely ignoring `NaN` values.

In [59]:
# Create an array with missing data (must be float)
data = np.array([1.0, 2.0, np.nan, 4.0, 5.0, np.nan])

print(f"Array with NaNs: {data}")

bool_miss =np.isnan(data)
print(f"is nan?: {bool_miss}")
print(f"count of nan: {np.sum(bool_miss)}")

Array with NaNs: [ 1.  2. nan  4.  5. nan]
is nan?: [False False  True False False  True]
count of nan: 2


In [61]:
print(f"sum of fails: {np.sum(data)}")

sum of fails: nan


In [62]:
print(f"safe sum: {np.nansum(data)}")

safe sum: 12.0


In [63]:
print(f"safe mean: {np.nanmean(data)}")

safe mean: 3.0


In [64]:
# 5. Removing NaNs
clean_data = data[~np.isnan(data)]
print(f"Data with NaNs removed: {clean_data}")

# 6. Filling NaNs with a value (e.g., 0)
filled_data = np.copy(data)
filled_data[np.isnan(filled_data)] = 0
print(f"Data with NaNs filled with 0: {filled_data}")

Data with NaNs removed: [1. 2. 4. 5.]
Data with NaNs filled with 0: [1. 2. 0. 4. 5. 0.]
